Support env flag in runbook converter tool (#889)
## Description
Updates the runbook converter tool to respect the `--env ` flag.

## Test plan
I created a runbook that only existed in the stage environment, and now this command works:
```
localcli tasks init --from-runbook test_runbook_stage_only --env stage
? Where is the script for this task? test_runbook_stage_only.airplane.ts
- Fetching details of runbook test_runbook_stage_only in env stage
- Getting resources associated with the runbook
- Converting block note to code
- Creating test_runbook_stage_only.airplane.ts
- Formatting code via prettier

✅ To complete your task:
- Write your task logic in test_runbook_stage_only.airplane.ts

🛫 To deploy your task to Airplane:
  airplane deploy test_runbook_stage_only.airplane.ts
```

Without this change, it would 404 because it was defaulting to the `prod` environment, where it doesn't exist:
```
localcli tasks init --from-runbook test_runbook_stage_only --env stage
? Where is the script for this task? test_runbook_stage_only.airplane.ts
- Fetching details of runbook test_runbook_stage_only

Error: Api: 404 - No runbook found

exit status 1
```