Disable task definition normalization in studio discoverer (#736)
## Description

Skips task definition normalization in the Studio during discovery, which allows the local dev server to start even if the task uses non-existent resources.

Depends on https://github.com/airplanedev/lib/pull/353

## Test plan
Before:
```
aplocal dev --studio ~/airplane/node_test/a.task.yaml
22:47:44 Loaded dev config from /Users/justinlu/airplane/node_test/airplane.dev.yaml
Discovering tasks and views...

Error: Resource with name or slug db not found, please create it using `airplane dev config set-resource`
```

Now:
```
aplocal dev --studio ~/airplane/node_test/a.task.yaml
22:47:20 Loaded dev config from /Users/justinlu/airplane/node_test/airplane.dev.yaml
Discovering tasks and views...
Found 1 task:
- my_task

Found 0 views:

The following tasks have resource attachments that are not defined in the dev config file. Please add them through the studio or run `airplane dev config set-resource`.
- my_task: [db]
```