Update dependency node-fetch to v3 (#164)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [node-fetch](https://togithub.com/node-fetch/node-fetch) | [`2.6.7` -> `3.2.6`](https://renovatebot.com/diffs/npm/node-fetch/2.6.7/3.2.6) | [![age](https://badges.renovateapi.com/packages/npm/node-fetch/3.2.6/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/npm/node-fetch/3.2.6/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/npm/node-fetch/3.2.6/compatibility-slim/2.6.7)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/npm/node-fetch/3.2.6/confidence-slim/2.6.7)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>node-fetch/node-fetch</summary>

### [`v3.2.6`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.2.6)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.2.5...v3.2.6)

##### Bug Fixes

-   undefined reference to response.body when aborted ([#&#8203;1578](https://togithub.com/node-fetch/node-fetch/issues/1578)) ([1c5ed6b](https://togithub.com/node-fetch/node-fetch/commit/1c5ed6b981e6c5dd28bd50f5ab5418e5bd262b99))

### [`v3.2.5`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.2.5)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.2.4...v3.2.5)

##### Bug Fixes

-   use space in accept-encoding values ([#&#8203;1572](https://togithub.com/node-fetch/node-fetch/issues/1572)) ([a92b5d5](https://togithub.com/node-fetch/node-fetch/commit/a92b5d5cf4457c2da95d8404b08cfd06a426a2fa)), closes [#&#8203;1571](https://togithub.com/node-fetch/node-fetch/issues/1571)

### [`v3.2.4`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.2.4)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.2.3...v3.2.4)

##### Bug Fixes

-   don't uppercase unknown methods ([#&#8203;1542](https://togithub.com/node-fetch/node-fetch/issues/1542)) ([004b3ac](https://togithub.com/node-fetch/node-fetch/commit/004b3ac8324e6cdbfb5d04b8bbdc6664ea48fbcf))

### [`v3.2.3`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.2.3)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.2.2...v3.2.3)

##### Bug Fixes

-   handle bom in text and json ([#&#8203;1482](https://togithub.com/node-fetch/node-fetch/issues/1482)) ([6425e20](https://togithub.com/node-fetch/node-fetch/commit/6425e2021a7def096e13dbabcac2f10e6da83d11))

### [`v3.2.2`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.2.2)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.2.1...v3.2.2)

##### Bug Fixes

-   add missing formdata export to types ([#&#8203;1518](https://togithub.com/node-fetch/node-fetch/issues/1518)) ([a4ea5f9](https://togithub.com/node-fetch/node-fetch/commit/a4ea5f9308f942400695cce261291d0a80cd1b02)), closes [#&#8203;1517](https://togithub.com/node-fetch/node-fetch/issues/1517)

### [`v3.2.1`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.2.1)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.2.0...v3.2.1)

##### Bug Fixes

-   cancel request example import ([#&#8203;1513](https://togithub.com/node-fetch/node-fetch/issues/1513)) ([61b3b5a](https://togithub.com/node-fetch/node-fetch/commit/61b3b5a06384003d332581080af6522bec19417f))

### [`v3.2.0`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.2.0)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.1.1...v3.2.0)

##### Features

-   export Blob, File and FormData + utilities ([#&#8203;1463](https://togithub.com/node-fetch/node-fetch/issues/1463)) ([81b1378](https://togithub.com/node-fetch/node-fetch/commit/81b1378bb3bda555d3d2114e7d3dfddbd91f210c))

### [`v3.1.1`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.1.1)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.1.0...v3.1.1)

#### Security patch release

Recommended to upgrade, to not leak sensitive cookie and authentication header information to 3th party host while a redirect occurred

#### What's Changed

-   core: update fetch-blob by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1371](https://togithub.com/node-fetch/node-fetch/pull/1371)
-   docs: Fix typo around sending a file by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1381](https://togithub.com/node-fetch/node-fetch/pull/1381)
-   core: (http.request): Cast URL to string before sending it to NodeJS core by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1378](https://togithub.com/node-fetch/node-fetch/pull/1378)
-   core: handle errors from the request body stream by [@&#8203;mdmitry01](https://togithub.com/mdmitry01) in [https://github.com/node-fetch/node-fetch/pull/1392](https://togithub.com/node-fetch/node-fetch/pull/1392)
-   core: Better handle wrong redirect header in a response by [@&#8203;tasinet](https://togithub.com/tasinet) in [https://github.com/node-fetch/node-fetch/pull/1387](https://togithub.com/node-fetch/node-fetch/pull/1387)
-   core: Don't use buffer to make a blob by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1402](https://togithub.com/node-fetch/node-fetch/pull/1402)
-   docs: update readme for TS [@&#8203;types/node-fetch](https://togithub.com/types/node-fetch) by [@&#8203;adamellsworth](https://togithub.com/adamellsworth) in [https://github.com/node-fetch/node-fetch/pull/1405](https://togithub.com/node-fetch/node-fetch/pull/1405)
-   core: Fix logical operator priority to disallow GET/HEAD with non-empty body by [@&#8203;maxshirshin](https://togithub.com/maxshirshin) in [https://github.com/node-fetch/node-fetch/pull/1369](https://togithub.com/node-fetch/node-fetch/pull/1369)
-   core: Don't use global buffer by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1422](https://togithub.com/node-fetch/node-fetch/pull/1422)
-   ci: fix main branch by [@&#8203;dnalborczyk](https://togithub.com/dnalborczyk) in [https://github.com/node-fetch/node-fetch/pull/1429](https://togithub.com/node-fetch/node-fetch/pull/1429)
-   core: use more node: protocol imports by [@&#8203;dnalborczyk](https://togithub.com/dnalborczyk) in [https://github.com/node-fetch/node-fetch/pull/1428](https://togithub.com/node-fetch/node-fetch/pull/1428)
-   core: Warn when using data by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1421](https://togithub.com/node-fetch/node-fetch/pull/1421)
-   docs: Create SECURITY.md by [@&#8203;JamieSlome](https://togithub.com/JamieSlome) in [https://github.com/node-fetch/node-fetch/pull/1445](https://togithub.com/node-fetch/node-fetch/pull/1445)
-   core: don't forward secure headers to 3th party by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1449](https://togithub.com/node-fetch/node-fetch/pull/1449)

#### New Contributors

-   [@&#8203;mdmitry01](https://togithub.com/mdmitry01) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1392](https://togithub.com/node-fetch/node-fetch/pull/1392)
-   [@&#8203;tasinet](https://togithub.com/tasinet) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1387](https://togithub.com/node-fetch/node-fetch/pull/1387)
-   [@&#8203;adamellsworth](https://togithub.com/adamellsworth) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1405](https://togithub.com/node-fetch/node-fetch/pull/1405)
-   [@&#8203;maxshirshin](https://togithub.com/maxshirshin) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1369](https://togithub.com/node-fetch/node-fetch/pull/1369)
-   [@&#8203;JamieSlome](https://togithub.com/JamieSlome) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1445](https://togithub.com/node-fetch/node-fetch/pull/1445)

**Full Changelog**: https://github.com/node-fetch/node-fetch/compare/v3.1.0...v3.1.1

### [`v3.1.0`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.1.0)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v3.0.0...v3.1.0)

#### What's Changed

-   fix(Body): Discourage form-data and buffer() by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1212](https://togithub.com/node-fetch/node-fetch/pull/1212)
-   fix: Pass url string to http.request by [@&#8203;serverwentdown](https://togithub.com/serverwentdown) in [https://github.com/node-fetch/node-fetch/pull/1268](https://togithub.com/node-fetch/node-fetch/pull/1268)
-   Fix octocat image link by [@&#8203;lakuapik](https://togithub.com/lakuapik) in [https://github.com/node-fetch/node-fetch/pull/1281](https://togithub.com/node-fetch/node-fetch/pull/1281)
-   fix(Body.body): Normalize `Body.body` into a `node:stream` by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/924](https://togithub.com/node-fetch/node-fetch/pull/924)
-   docs(Headers): Add default Host request header to README.md file by [@&#8203;robertoaceves](https://togithub.com/robertoaceves) in [https://github.com/node-fetch/node-fetch/pull/1316](https://togithub.com/node-fetch/node-fetch/pull/1316)
-   Update CHANGELOG.md by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1292](https://togithub.com/node-fetch/node-fetch/pull/1292)
-   Add highWaterMark to cloned properties by [@&#8203;davesidious](https://togithub.com/davesidious) in [https://github.com/node-fetch/node-fetch/pull/1162](https://togithub.com/node-fetch/node-fetch/pull/1162)
-   Update README.md to fix HTTPResponseError by [@&#8203;thedanfernandez](https://togithub.com/thedanfernandez) in [https://github.com/node-fetch/node-fetch/pull/1135](https://togithub.com/node-fetch/node-fetch/pull/1135)
-   docs: switch `url` to `URL` by [@&#8203;dhritzkiv](https://togithub.com/dhritzkiv) in [https://github.com/node-fetch/node-fetch/pull/1318](https://togithub.com/node-fetch/node-fetch/pull/1318)
-   fix(types): declare buffer() deprecated by [@&#8203;dnalborczyk](https://togithub.com/dnalborczyk) in [https://github.com/node-fetch/node-fetch/pull/1345](https://togithub.com/node-fetch/node-fetch/pull/1345)
-   chore: fix lint by [@&#8203;dnalborczyk](https://togithub.com/dnalborczyk) in [https://github.com/node-fetch/node-fetch/pull/1348](https://togithub.com/node-fetch/node-fetch/pull/1348)
-   refactor: use node: prefix for imports by [@&#8203;dnalborczyk](https://togithub.com/dnalborczyk) in [https://github.com/node-fetch/node-fetch/pull/1346](https://togithub.com/node-fetch/node-fetch/pull/1346)
-   Bump data-uri-to-buffer from 3.0.1 to 4.0.0 by [@&#8203;dependabot](https://togithub.com/dependabot) in [https://github.com/node-fetch/node-fetch/pull/1319](https://togithub.com/node-fetch/node-fetch/pull/1319)
-   Bump mocha from 8.4.0 to 9.1.3 by [@&#8203;dependabot](https://togithub.com/dependabot) in [https://github.com/node-fetch/node-fetch/pull/1339](https://togithub.com/node-fetch/node-fetch/pull/1339)
-   Referrer and Referrer Policy by [@&#8203;tekwiz](https://togithub.com/tekwiz) in [https://github.com/node-fetch/node-fetch/pull/1057](https://togithub.com/node-fetch/node-fetch/pull/1057)
-   Add typing for Response.redirect(url, status) by [@&#8203;c-w](https://togithub.com/c-w) in [https://github.com/node-fetch/node-fetch/pull/1169](https://togithub.com/node-fetch/node-fetch/pull/1169)
-   chore: Correct stuff in README.md by [@&#8203;Jiralite](https://togithub.com/Jiralite) in [https://github.com/node-fetch/node-fetch/pull/1361](https://togithub.com/node-fetch/node-fetch/pull/1361)
-   docs: Improve clarity of "Loading and configuring" by [@&#8203;serverwentdown](https://togithub.com/serverwentdown) in [https://github.com/node-fetch/node-fetch/pull/1323](https://togithub.com/node-fetch/node-fetch/pull/1323)
-   feat(Body): Added support for `BodyMixin.formData()` and constructing bodies with FormData by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1314](https://togithub.com/node-fetch/node-fetch/pull/1314)
-   template: Make PR template more task oriented  by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1224](https://togithub.com/node-fetch/node-fetch/pull/1224)
-   docs: Update code examples by [@&#8203;jimmywarting](https://togithub.com/jimmywarting) in [https://github.com/node-fetch/node-fetch/pull/1365](https://togithub.com/node-fetch/node-fetch/pull/1365)

#### New Contributors

-   [@&#8203;serverwentdown](https://togithub.com/serverwentdown) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1268](https://togithub.com/node-fetch/node-fetch/pull/1268)
-   [@&#8203;lakuapik](https://togithub.com/lakuapik) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1281](https://togithub.com/node-fetch/node-fetch/pull/1281)
-   [@&#8203;robertoaceves](https://togithub.com/robertoaceves) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1316](https://togithub.com/node-fetch/node-fetch/pull/1316)
-   [@&#8203;davesidious](https://togithub.com/davesidious) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1162](https://togithub.com/node-fetch/node-fetch/pull/1162)
-   [@&#8203;thedanfernandez](https://togithub.com/thedanfernandez) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1135](https://togithub.com/node-fetch/node-fetch/pull/1135)
-   [@&#8203;dhritzkiv](https://togithub.com/dhritzkiv) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1318](https://togithub.com/node-fetch/node-fetch/pull/1318)
-   [@&#8203;dnalborczyk](https://togithub.com/dnalborczyk) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1345](https://togithub.com/node-fetch/node-fetch/pull/1345)
-   [@&#8203;dependabot](https://togithub.com/dependabot) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1319](https://togithub.com/node-fetch/node-fetch/pull/1319)
-   [@&#8203;c-w](https://togithub.com/c-w) made their first contribution in [https://github.com/node-fetch/node-fetch/pull/1169](https://togithub.com/node-fetch/node-fetch/pull/1169)

**Full Changelog**: https://github.com/node-fetch/node-fetch/compare/v3.0.0...v3.1.0

### [`v3.0.0`](https://togithub.com/node-fetch/node-fetch/releases/tag/v3.0.0)

[Compare Source](https://togithub.com/node-fetch/node-fetch/compare/v2.6.7...v3.0.0)

version 3 is going out of a long beta period and switches to stable

One major change is that it's now a ESM only package
See [changelog](https://togithub.com/node-fetch/node-fetch/blob/main/docs/CHANGELOG.md#v300) for more information about all the changes.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 5am on Thursday" in timezone America/New_York, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click this checkbox.