Polish init-dev command and switch to init (#612)
## Description
Root-level init command. Going to remove the `dev` flag for this when we are ready to release views and templates more broadly.

This makes the polish changes from design review: https://linear.app/airplane/issue/VIEW-164/polish-airplane-init-dev 


## Test plan

airplane init without --dev or --template defaults to task init 
```
➜  test0829 ~/airplanedev/cli/bin/airplane init     
? What should this task be called? 

Error: Interrupt
```


airplane init with --dev goes down path of asking you what to init 

```
➜  test0829 ~/airplanedev/cli/bin/airplane init --dev
? What would you like to initialize? Template   Clone ready-made tasks and views to start developing faster
? Which template would you like to initialize? Getting started (getting_started)
? Directory getting_started already exists. Do you want to remove its existing files and continue? Yes
- Created directory getting_started
- Copied getting_started/README.md
- Copied getting_started/customer_dashboard/customer_dashboard.view.tsx
- Copied getting_started/customer_dashboard/customer_dashboard.view.yaml
- Copied getting_started/package.json
- Copied getting_started/tasks/list_accounts.sql
- Copied getting_started/tasks/list_accounts.task.yaml
- Copied getting_started/tasks/list_users.sql
- Copied getting_started/tasks/list_users.task.yaml
- Copied getting_started/tasks/promote_account_user.sql
- Copied getting_started/tasks/promote_account_user.task.yaml
- Copied getting_started/tasks/update_account.sql
- Copied getting_started/tasks/update_account.task.yaml
- Copied getting_started/tsconfig.json
- Installing dependencies...
- Finished installing dependencies

Previewing getting_started/README.md:
# Next steps for Views getting started

1. Navigate to the getting_started directory: `cd views_getting_started`
2. Deploy tasks: `airplane deploy tasks --yes`
3. Develop your view locally: `airplane views dev`
4. Visit the getting started guide for Airplane Views to continue building your view: https://docs.airplane.dev/views/getting-started
5. Deploy your view: `airplane deploy .`
```

airplane init --template works as expected
```
➜  test0829 ~/airplanedev/cli/bin/airplane init --template=getting_started
? Directory getting_started already exists. Do you want to remove its existing files and continue? Yes
- Created directory getting_started
- Copied getting_started/README.md
- Copied getting_started/customer_dashboard/customer_dashboard.view.tsx
- Copied getting_started/customer_dashboard/customer_dashboard.view.yaml
- Copied getting_started/package.json
- Copied getting_started/tasks/list_accounts.sql
- Copied getting_started/tasks/list_accounts.task.yaml
- Copied getting_started/tasks/list_users.sql
- Copied getting_started/tasks/list_users.task.yaml
- Copied getting_started/tasks/promote_account_user.sql
- Copied getting_started/tasks/promote_account_user.task.yaml
- Copied getting_started/tasks/update_account.sql
- Copied getting_started/tasks/update_account.task.yaml
- Copied getting_started/tsconfig.json
- Installing dependencies...
- Finished installing dependencies

Previewing getting_started/README.md:
# Next steps for Views getting started

1. Navigate to the getting_started directory: `cd views_getting_started`
2. Deploy tasks: `airplane deploy tasks --yes`
3. Develop your view locally: `airplane views dev`
4. Visit the getting started guide for Airplane Views to continue building your view: https://docs.airplane.dev/views/getting-started
5. Deploy your view: `airplane deploy .`
```