Add generating inline code for workflows (#271)
## Description
Adds support for `airplane task init --workflow` which generates an inline template file for workflows.

Note that workflow implies inline.

cc @ameyakhare 

Depends on https://github.com/airplanedev/cli/pull/636/files

## Test plan

- [x] Tested init with inline
```
❯ cli (kelly/support-inline-workflow) ✔ localcli tasks init --inline
? What should this task be called? test_inline
? What kind of task should this be? Node
? Where is the script for this task? test_inline.airplane.ts
- Created test_inline.airplane.ts

✅ To complete your task:
- Write your task logic in test_inline.airplane.ts
- Add a description, parameters, and more details in test_inline.airplane.ts

⚡ To execute the task locally:
  airplane dev test_inline.airplane.ts

🛫 To deploy your task to Airplane:
  airplane deploy test_inline.airplane.ts
❯ cli (kelly/support-inline-workflow) ✘ cat test_inline.airplane.ts
import airplane from "airplane"

export default airplane.task(
  {
    slug: "test_inline",
    name: "test_inline",
    nodeVersion: "18",
  },
  () => {
    // Put the main logic of the task in this function.
    console.log('Hello world!');

    // You can return data to show outputs to users.
    // Outputs documentation: https://docs.airplane.dev/tasks/outputs
    return [
        {element: 'hydrogen', weight: 1.008},
        {element: 'helium', weight: 4.0026},
    ];
  }
)
```

- [x] Test init with workflow 
```
❯ cli (kelly/support-inline-workflow) ✘ localcli tasks init --workflow
? What should this task be called? workflow_test
? What kind of task should this be? Node
? Where is the script for this task? workflow_test.airplane.ts
- Created workflow_test.airplane.ts

✅ To complete your task:
- Write your task logic in workflow_test.airplane.ts
- Add a description, parameters, and more details in workflow_test.airplane.ts

⚡ To execute the task locally:
  airplane dev workflow_test.airplane.ts

🛫 To deploy your task to Airplane:
  airplane deploy workflow_test.airplane.ts
❯ cli (kelly/support-inline-workflow) ✘ cat workflow_test.airplane.ts
import airplane from "airplane"

export default airplane.workflow(
  {
    slug: "workflow_test",
    name: "workflow_test",
    nodeVersion: "18",
  },
  () => {
    // Put the main logic of the task in this function.
    console.log('Hello world!');

    // You can return data to show outputs to users.
    // Outputs documentation: https://docs.airplane.dev/tasks/outputs
    return [
        {element: 'hydrogen', weight: 1.008},
        {element: 'helium', weight: 4.0026},
    ];
  }
)
```

- [x] verified that validation works on both:
```
❯ cli (kelly/support-inline-workflow) ✘ localcli tasks init --workflow
? What should this task be called? etset
? What kind of task should this be? REST

Error: Inline config is only supported for Node tasks.

exit status 1
❯ cli (kelly/support-inline-workflow) ✘ localcli tasks init --inline
? What should this task be called? sdgdsg
? What kind of task should this be? REST

Error: Inline config is only supported for Node tasks.

exit status 1
```