Make tsconfig parsing more flexible (#960)
## Description
This change updates our CLI to accept tsconfig files that have trailing commas and comments. Apparently, tsconfig files allow for these features even though they're technically not valid JSON (see https://github.com/microsoft/TypeScript/issues/20384#issuecomment-348552936). Some users reported errors with `airplane tasks init` due to this.

Note that our tsconfig conversion logic will remove these features from the original if changes are needed. Hopefully this will not be a pain for users (and they can revert and manually apply our suggested changes later if needed).

## Test plan
Testing completed successfully via running `airplane tasks init` with the current and new versions with a tsconfig file with trailing commas:

#### Current
```
Benjamin-Yolkens-MacBook-Pro:js2 benjaminyolken$ cat tsconfig.json 
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["ESNext"],
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitAny": false,
    "module": "ESNext",
    "moduleResolution": "node",
    "isolatedModules": true,
    "noEmit": true,
  },
  "exclude": ["node_modules"]
}
Benjamin-Yolkens-MacBook-Pro:js2 benjaminyolken$ 

Benjamin-Yolkens-MacBook-Pro:js2 benjaminyolken$ airplane tasks init
? What should this task be called? hello2
? What kind of task should this be? JavaScript
? Where is the script for this task? hello2.airplane.ts
- Created hello2.airplane.ts

Error: Invalid character '}' looking for beginning of object key string
```

#### New
```
Benjamin-Yolkens-MacBook-Pro:js2 benjaminyolken$ ~/go/bin/airplane tasks init
? What should this task be called? hello3
? What kind of task should this be? JavaScript
? Where is the script for this task? hello3.airplane.ts
- Created hello3.airplane.ts

✅ To complete your task:
- Write your task logic in hello3.airplane.ts
- Configure your task with parameters, a description and more in hello3.airplane.ts

⚡ To develop the task locally:
  airplane dev hello3.airplane.ts

🛫 To deploy your task to Airplane:
  airplane deploy hello3.airplane.ts
```