Print parsing errors as debug logs (#222)
## Description

If the node parser encountered an error, we previously did not show any output. We now log stderr as debug lines.

The underlying user error was that I was accessing a field on a possibly undefined object.

Even though the stderr text is included in the returned error, our CLI doesn't seem to print the error message. We'll want to debug this separately.

```
examples ▶ lairlocal deploy ./node/displays/displays.aptask.ts --local --debug
[Sentry] 2022/08/10 08:55:15 Sentry client initialized with an empty DSN. Using noopTransport. No events will be delivered.
[Sentry] 2022/08/10 08:55:15 Integration installed: ContextifyFrames
[Sentry] 2022/08/10 08:55:15 Integration installed: Environment
[Sentry] 2022/08/10 08:55:15 Integration installed: Modules
[Sentry] 2022/08/10 08:55:15 Integration installed: IgnoreErrors
[debug] Version: <unknown> (<unknown>)
[debug] performing request GET https://api.airplane.so:5000/v0/auth/info
[debug] Error: exit status 1
[debug] parsing file="./node/displays/displays.aptask.ts": /Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:859
[debug]     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
[debug]            ^
[debug] TSError: ⨯ Unable to compile TypeScript:
[debug] node/displays/displays.aptask.ts(19,36): error TS2533: Object is possibly 'null' or 'undefined'.
[debug]
[debug]     at createTSError (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:859:12)
[debug]     at reportTSError (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:863:19)
[debug]     at getOutput (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:1077:36)
[debug]     at Object.compile (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:1433:41)
[debug]     at Module.m._compile (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:1617:30)
[debug]     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[debug]     at Object.require.extensions.<computed> [as .ts] (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:1621:12)
[debug]     at Module.load (node:internal/modules/cjs/loader:981:32)
[debug]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[debug]     at Module.require (node:internal/modules/cjs/loader:1005:19) {
[debug]   diagnosticCodes: [ 2533 ]
[debug] }
[debug]
[debug] github.com/airplanedev/lib/pkg/deploy/discover.parseNodeDefinitions
[debug] 	/Users/colin/dev/github.com/airplanedev/lib/pkg/deploy/discover/code_task_discover.go:130
[debug] github.com/airplanedev/lib/pkg/deploy/discover.parseDefinitions
[debug] 	/Users/colin/dev/github.com/airplanedev/lib/pkg/deploy/discover/code_task_discover.go:107
[debug] github.com/airplanedev/lib/pkg/deploy/discover.(*CodeTaskDiscoverer).GetTaskConfigs
[debug] 	/Users/colin/dev/github.com/airplanedev/lib/pkg/deploy/discover/code_task_discover.go:52
[debug] github.com/airplanedev/lib/pkg/deploy/discover.(*Discoverer).Discover
[debug] 	/Users/colin/dev/github.com/airplanedev/lib/pkg/deploy/discover/discover.go:136
[debug] github.com/airplanedev/cli/cmd/airplane/tasks/deploy.run
[debug] 	/Users/colin/dev/github.com/airplanedev/cli/cmd/airplane/tasks/deploy/deploy.go:150
[debug] github.com/airplanedev/cli/cmd/airplane/tasks/deploy.New.func1
[debug] 	/Users/colin/dev/github.com/airplanedev/cli/cmd/airplane/tasks/deploy/deploy.go:66
[debug] github.com/spf13/cobra.(*Command).execute
[debug] 	/Users/colin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872
[debug] github.com/spf13/cobra.(*Command).ExecuteC
[debug] 	/Users/colin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
[debug] github.com/spf13/cobra.(*Command).Execute
[debug] 	/Users/colin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
[debug] github.com/spf13/cobra.(*Command).ExecuteContext
[debug] 	/Users/colin/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:911
[debug] main.main
[debug] 	/Users/colin/dev/github.com/airplanedev/cli/cmd/airplane/main.go:27
[debug] runtime.main
[debug] 	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/proc.go:250
[debug] runtime.goexit
[debug] 	/opt/homebrew/Cellar/go/1.19/libexec/src/runtime/asm_arm64.s:1165

Error: Exit status 1

[Sentry] 2022/08/10 08:55:17 Event dropped due to noopTransport usage.
[debug] Sentry event ID: 492bc3fb5c914f60b1620721c3f70965
```

## Test plan