Switch to tsx for code task discover (#237)
## Description

For context, I switched our [node-sdk examples to config-as-code](https://github.com/airplanedev/node-sdk/blob/colin-08-19-Add_new_display_methods/examples/standard/main.airplane.ts). Unfortunately, they fail when deployed:

```
node-sdk ▶ lairlocal deploy ./examples/standard/main.airplane.ts --debug
[Sentry] 2022/08/23 14:10:08 Sentry client initialized with an empty DSN. Using noopTransport. No events will be delivered.
[Sentry] 2022/08/23 14:10:08 Integration installed: ContextifyFrames
[Sentry] 2022/08/23 14:10:08 Integration installed: Environment
[Sentry] 2022/08/23 14:10:08 Integration installed: Modules
[Sentry] 2022/08/23 14:10:08 Integration installed: IgnoreErrors
[debug] Version: <unknown> (<unknown>)
[debug] performing request GET https://api.airplane.so:5000/v0/auth/info
[debug] Error: exit status 1
[debug] parsing file="/Users/colin/dev/github.com/airplanedev/node-sdk/.airplane/examples/standard/main.airplane.js": /Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:859
[debug]     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
[debug]            ^
[debug] TSError: ⨯ Unable to compile TypeScript:
[debug] packages/airplane/internal/api/fetcher.ts(6,17): error TS2732: Cannot find module '../../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
[debug]
[debug]     at createTSError (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:859:12)
[debug]     at reportTSError (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:863:19)
[debug]     at getOutput (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:1077:36)
[debug]     at Object.compile (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:1433:41)
[debug]     at Module.m._compile (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:1617:30)
[debug]     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
[debug]     at Object.require.extensions.<computed> [as .ts] (/Users/colin/.npm/_npx/49c62d028eafcc6e/node_modules/ts-node/src/index.ts:1621:12)
[debug]     at Module.load (node:internal/modules/cjs/loader:998:32)
[debug]     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
[debug]     at Module.require (node:internal/modules/cjs/loader:1022:19) {
[debug]   diagnosticCodes: [ 2732 ]
```

This can be fixed by adding the `--resolveJsonModule` into the tsconfig passed to `ts-node`:

```diff
out, err := exec.Command("npx", "-p", "typescript", "-p", "@types/node", "-p", "ts-node",
-		"ts-node", "-O", "{\"strict\": false}", tempFile.Name(), file).Output()
+		"ts-node", "-O", "{\"strict\": false, \"resolveJsonModule\": true}", tempFile.Name(), file).Output()
```

However, this issue (and the need for disabling strict checking) stem from how `ts-node` is using the TS compiler under the hood. We don't want to type-check user code. We can sidestep this by either using the `ts-node --swc` flag or switching to [`tsx`](https://github.com/esbuild-kit/tsx) which builds on `esbuild`. This PR does the latter since it mirrors how we use `esbuild` elsewhere. See [a technical comparison here](https://github.com/privatenumber/ts-runtime-comparison).

## Test plan

Confirm you can deploy the config-as-code tasks in the `node-sdk` PR linked above.