Init with getting started example for views init --getting-started flag (#559)
## Description
--getting-started flag now works as expected

## Test plan


```
➜  test0802 ~/airplanedev/cli/bin/airplane views init --getting-started
- Created folder getting_started
- Copied getting_started/customer_dashboard/customer_dashboard.view.tsx
- Copied getting_started/customer_dashboard/customer_dashboard.view.yaml
- Copied getting_started/package.json
- Copied getting_started/tasks/list_accounts.sql
- Copied getting_started/tasks/list_accounts.task.yaml
- Copied getting_started/tasks/list_users.sql
- Copied getting_started/tasks/list_users.task.yaml
- Copied getting_started/tasks/promote_account_user.sql
- Copied getting_started/tasks/promote_account_user.task.yaml
- Copied getting_started/tasks/update_account.sql
- Copied getting_started/tasks/update_account.task.yaml
- Copied getting_started/tsconfig.json
- Installing dependencies...
- Finished installing dependencies

⚡ To develop your view locally:
  airplane views dev getting_started

🛫 To deploy your view to Airplane:
  airplane deploy getting_started
➜  test0802  ~/airplanedev/cli/bin/airplane views dev getting_started
Started development server at http://localhost:5173/ (^C to quit)
Press ENTER to preview your view in the browser

^Ctrap: received "interrupt"

Error: Signal: interrupt

➜  test0802  ~/airplanedev/cli/bin/airplane deploy getting_started   
? A view with slug customer_dashboard_getting_started does not exist. Would you like to create one? No
[warning] View with slug customer_dashboard_getting_started does not exist, skipping deployment.
Deploying 4 tasks:
```