Skip registering tasks that have no registered runtime (#622)
## Description
REST tasks currently are the only task type that doesn't have a runtime- they don't have a local entry point. Instead of erroring while registering tasks and views, we should skip REST tasks. Adds a debug statement in case we need to debug this later. The message to users for a task that doesn't support local execution or doesn't have a runtime is the same- since to them they're both unsupported.

Before:
Trying to start the server with some REST tasks would cause it to quit:
```
Discovering tasks and views...
Found 2 tasks:
- hello world py
- rest task

Found 0 views:

Error: Did not find any runtimes for task type
```

After:
```
 localcli dev --editor /Users/kellytrinh/go/src/github.com/airplanedev/tasks-test
Discovering tasks and views...
Found 2 tasks:
- test rest
- test  rest1

Found 0 views:

Skipping 2 unsupported tasks or views:
- test rest: rest task does not support local execution
- test  rest1: rest task does not support local execution

Visit https://app.airplane.so:5000/editor?host=http://localhost:4000 for a development UI.
[Ctrl+C] to shutdown the local dev server.
```


## Test plan
- [x] start server in a directory that has both rest and supported tasks