Default overwrite file/folder to false when cloning templates (#687)
## Description
We want to default to false so we don't accidentally overwrite user's folders

## Test plan

```
➜  test0919 ~/airplanedev/cli/bin/airplane init --template=admin_panel
? Directory admin_panel already exists. Do you want to remove its existing files and continue? (y/N) 

Error: Canceled creating directory admin_panel
```

pressing enter defaults to n