Allow strings for bases (#404)
## Description
This change updates the kind options parsing in lib to accept strings for task bases; when the struct comes from the API, golang doesn't know that the type should be a specialized type, I think, and thus treats it as a regular string.

I'm getting this error when trying to deploy a task with a base set, and I think this will fix it:

```
Benjamin-Yolkens-MacBook-Pro:node benjaminyolken$ airplane deploy ./js_deploy_test_e2e.task.yaml 
Deploying 1 task:

js_deploy_test_e2e
Type: node
Root directory: ./
Definition file: ./js_deploy_test_e2e.task.yaml
URL: https://app.airplane.dev/t/js_deploy_test_e2e

Error: Expected string base, got string instead
```

## Test plan
Testing not required because this is just allowing a string instead of an aliased string.